### ISSUE TITLE
Bulletproofs status

### ISSUE THREAD

**Issue by i0x71** [ing-bank/zkrp#12]
Hi,
I noticed that README mentions that bulletrpoofs may be incomplete: 
"However, this functionalities were not yet implemented and should be considered as future work. In particular, Bulletproofs seems an interesting building block to construct private smart contracts."

Is that still the case ?
Are they complete enough to be used in production ?

Thanks alot

**Comment by mvdbos** [comment]
This statement is still correct. We have not added new functionality to the library since then. We are currently not focussed on expanding this library.

As for production readiness: like with many other ZKP-related libraries available now, we do not guarantee production readiness right now. Use at your own risk.
